### ISSUE TITLE
Anything else?

### ISSUE THREAD

**Issue by jamadden** [OpenNTI/nti.i18n#1]
I think we only need the country and tld data, so that's all I ported so far. I couldn't find any other uses of plone.i18n in our code. Do we need anything else, or is this sufficient to release? It will definitely meet the needs of `nti.schema`.

The TLD list is up-to-date with that published by IANA this morning (and can be easily updated by downloding the new file). I've been told we have patches to add new data to the old plone.i18n, but I'm not sure if its TLD data or country data (I haven't been able to find it). So long as it was TLD data, and we didn't need/have specific languages for it, we should be fine.

/cc @papachoco

**Comment by papachoco** [comment]
In /nti.monkey/src/nti/monkey/patch_plone_i18n_on_import.py we are parsing a CSV from IANA (March / 2017) and only taking the domain and updating plone_i18n.

**Comment by jamadden** [comment]
Well this is the current IANA data, so we should be good there. What about the API, is there anything I missed?

**Comment by papachoco** [comment]
nti.schema tries to use parse for ICountryAvailability utility
nti.dataserver uses ICcTLDInformation utility to get the getAvailableTLDs to validate email addresses

**Comment by jamadden** [comment]
Yup, those are the two APIs implemented here, and the only uses I could find in our other code.

**Comment by jamadden** [comment]
I'm going to go ahead and release this as-is and update nti.schema to depend on it, and we can go from there if needed.

Thanks!

**Comment by papachoco** [comment]
Thanks
